baseURL = 'https://godotrecipes.com/godot_recipes/4.x/'
languageCode = 'en-us'
defaultContentLanguage = 'en'
publishDir = "../docs/4.x"
title = 'Godot 4 Recipes'
theme = "hugo-theme-relearn-main"
pygmentsStyle = "nord"
pygmentsCodeFences = true
staticDir = ["static", "../static_shared"]
themesDir = "../themes_shared"

[languages]
  [languages.en]
    languageName = "English"
    contentDir = "content"
    weight = 1

    [[languages.en.menu.shortcuts]]
    name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
    identifier = "ds"
    url = "https://github.com/kidscancode/godot_recipes"
    weight = 10

    [[languages.en.menu.shortcuts]]
    name = "<i class='fas fa-tags'></i>&nbsp;Tags"
    url = "/tags"
    weight = 50

    [[languages.en.menu.shortcuts]]
    name = "<i class='fas fa-fw fa-bookmark'></i> Godot Docs"
    identifier = "godotdocs"
    url = "https://docs.godotengine.org/"
    weight = 40

  [languages.ja]
    languageName = "日本語"
    contentDir = "content"
    weight = 2
    title = 'Godot 4 レシピ'

    [[languages.ja.menu.shortcuts]]
    name = "<i class='fab fa-fw fa-github'></i> GitHubリポジトリ"
    identifier = "ds1"
    url = "https://github.com/kamera25/godot_recipes"
    weight = 10

    [[languages.ja.menu.shortcuts]]
    name = "<i class='fab fa-fw fa-github'></i> GitHubリポジトリ(原文)"
    identifier = "ds2"
    url = "https://github.com/kidscancode/godot_recipes"
    weight = 20

    [[languages.ja.menu.shortcuts]]
    name = "<i class='fas fa-fw fa-book'></i> Kids Can Code"
    identifier = "kcc"
    url = "https://kidscancode.org/godot_recipes/"
    weight = 45

    [[languages.ja.menu.shortcuts]]
    name = "<i class='fas fa-tags'></i>&nbsp;タグ"
    url = "/ja/tags"
    weight = 50

    [[languages.ja.menu.shortcuts]]
    name = "<i class='fas fa-fw fa-bookmark'></i> Godotドキュメント"
    identifier = "godotdocs"
    url = "https://docs.godotengine.org/ja/"
    weight = 40

[params]
    disableNextPrev = true
    themeVariant = ["auto", "relearn-light", "relearn-dark", "neon"]
    disableInlineCopyToClipBoard = true
    godotVer = "4.x"
    godotVerToggle = "3.x"
    landingPageURL = "/godot_recipes/4.x/"
    disableLandingPageButton = true

[outputs]
    home = [ "HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
    unsafe = true

[minify]
  minifyOutput = true